export const SET_DROP_TIME = 'SET_DROP_TIME';
export const SET_GAME_OVER = 'SET_GAME_OVER';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_BUTTON_COUNT = 'SET_BUTTON_COUNT';
